<?php

/**
 * @file
 * Primary module hooks for Db module module.
 */

use Drupal\db_module\Entity\Bundle\PageBundle;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function db_module_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['page'])) {
    $bundles['node']['page']['class'] = PageBundle::class;
  }
}

/**
 * Implements hook_theme().
 */
function db_module_theme($existing, $type, $theme, $path) {
  return [
    'my_template' => [
      'variables' => [
        'event_per_year' => NULL,
        'event_per_quarter' => NULL,
        'event_per_type' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function db_module_preprocess_page(&$variables) {
  $context_data = [
    'formId' => 'db_module_taxonomy',
  ];
  $variables['page']['#attached']['drupalSettings']['db_module']['formContext'] = $context_data;
}

/**
 * Implements hook_views_query_alter().
 */
function db_module_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'movies' && $query->displayHandler->getPluginId() == 'page') {
    $query->orderby = [
      [
        'field' => 'field_price_value',
        'direction' => 'ASC',
      ],
    ];
  }
}
